{% set name = "auto-sklearn" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c574720c787efba36c6a734f10af747c73aa369a0a0046e37d5bcdd8c7ef94d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - configspace >=0.4.14,<0.5
    - dask-core <2021.07
    - distributed >=2.2.0,<2021.07
    - joblib
    - liac-arff
    - numpy >=1.9.0
    - pandas >=1.0
    - pynisher >=0.6.3
    - pyrfr >=0.8.1,<0.9
    - python >=3.7
    - pyyaml
    - scikit-learn >=0.24.0,<0.25.0
    - scipy >=1.7.0
    - setuptools
    - smac >=0.14
    - threadpoolctl
    - typing_extensions
    - __linux

test:
  imports:
    - autosklearn
    - autosklearn.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://automl.github.io/auto-sklearn
  summary: Automated machine learning.
  description: |
    auto-sklearn is an automated machine learning toolkit and a drop-in replacement for a scikit-learn estimator.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://automl.github.io/auto-sklearn/master/manual.html
  dev_url: https://github.com/automl/auto-sklearn

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
