{% set name = "auto-sklearn" %}
{% set version = "0.14.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: cdcad93a562ab0664a84d0c71fdb56624f7541f81de3c30272e5ec3447fc428a
  - url: https://raw.githubusercontent.com/automl/automl_common/main/LICENSE
    sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4
    # automl_common license

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - configspace >=0.4.14,<0.5
    - dask >=2021.12
    - distributed >=2012.12
    - distro
    - joblib
    - liac-arff
    - numpy >=1.9.0
    - pandas >=1.0
    - pynisher >=0.6.3
    - pyrfr >=0.8.1,<0.9
    - python >=3.7
    - pyyaml
    - scikit-learn >=0.24.0,<0.25.0
    - scipy >=1.7.0
    - setuptools
    - smac >=0.14
    - threadpoolctl
    - typing_extensions
    - __linux

test:
  imports:
    - autosklearn
    - autosklearn.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://automl.github.io/auto-sklearn
  summary: Automated machine learning.
  description: |
    auto-sklearn is an automated machine learning toolkit and a drop-in replacement for a scikit-learn estimator.
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE.txt
    - LICENSE
  doc_url: https://automl.github.io/auto-sklearn/master/manual.html
  dev_url: https://github.com/automl/auto-sklearn

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
